application: aspy
version: 2
runtime: php
api_version: 1
threadsafe: true

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|txt))$
  static_files: \1
  upload: .+\.(gif|png|jpg|txt)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1