application: aspy
version: 2
runtime: php
api_version: 1
threadsafe: true

handlers:
# Serve images as static resources.
- url: /up/(.*)$
  static_files: \1
  upload: /up/(.*)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1